# Site settings
title: Bryon Urbanec UI/UX Designer

description: Bryon Urbanec - Designer and web builder valuing user-centered design and development.

baseurl: "" # the subpath of your site, e.g. /blog/
# Build settings
markdown: kramdown

highlighter: rouge

exclude: ['node_modules', ‘css’, ‘_scss’]
keep_files: ['_site/css']

github_username:  b-ry

navigation: 
# - text: Work
#   url: /work
# - text: About
#   url: /about

# - text: Thoughts
  # url: /thoughts


collections:

  work:
    output: true
    permalink: /work/:name
  lab:
    output: true
    permalink: /lab/:name
