# Site settings
title: Bryon Urbanec Portfolio

baseurl: "" # the subpath of your site, e.g. /blog/
# Build settings
markdown: kramdown

exclude: ['node_modules', ‘css’, ‘_scss’]
keep_files: ['_site/css']

github_username:  b-ry

navigation: 
# - text: Work
#   url: /work
# - text: About
#   url: /about

# - text: Thoughts
  # url: /thoughts


collections:
  work:
    output: true
    permalink: /work/:name
